//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHL_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joukkue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Joukkue()
        {
            this.Pelaajas = new HashSet<Pelaaja>();
        }
    
        public int idJoukkue { get; set; }
        public string Nimi { get; set; }
        public int Voitot { get; set; }
        public int Häviöt { get; set; }
        public string Jatkoaikahäviöt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pelaaja> Pelaajas { get; set; }
    }
}
