//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHL_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelaaja
    {
        public int idPelaaja { get; set; }
        public string Nimi { get; set; }
        public int Pelinumero { get; set; }
        public int Maalit { get; set; }
        public int Syötöt { get; set; }
        public int Plusminus { get; set; }
        public int idJoukkue { get; set; }
    
        public virtual Joukkue Joukkue { get; set; }
    }
}
